import Link from "next/link";
import { Products } from "../types";
import { Metadata } from "next";


export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};

export default async function ProductPage() {
    const data = await fetch("http://localhost:3001/products")
    const posts = await data.json() as Products[];

    return (
        <div>
            <h1>Product Page</h1>
            <div>
                {posts.map((post) => (
                    <div key={post.id}>
                        <Link href={`/products/${post.slug}`}>{post.title}</Link>
                    </div>
                ))}
            </div>
        </div>
    )
}


